travis:
  secure:
    BINSTAR_TOKEN: txmW5y4AF7V1GUmAjltD6H9IARQFiJ5Whv1RKwnLL3Pa2jyCzyJyEHlfhsO3jA3uSFlflECHCSSJCzSK3mXc+YZOv+Z5apecw63rGy7g8hZ3AfQ+7O8POoT1/pnYfjUA/DGxzrPZDcnAZDoBoFdWcxfcfnt/JTTxelTrMcQafs54YidY1cfaAUhCb3ki5e4evsz/2aMUklVmP9yxtTSby8rjMNa8Iol2FfTgTxs4C6OK3wrHAR3hNmK4P82+OWeb1t3gYigDdaVMJ9IVa/vdlFPprSjGbegdRuYp7zuOl4alxVzDgDJRnOd7AGVqFZoTwB8+lNGYvHtGif2/H1Ut3YZdVLzi7Ti+JR20PzOPZ9pysQI7kPfZAeOoSxtTYBLp5OsyLu+zNrVGKWeyDJZYYj/dyskcgd+S9W0yJXAJVQbUgOKWrQkhguGe7r74tLCOvD8asV3IVJmWsnu7fP+ZpwIjuLGhXLgu0E0LmGy6QITRZyrs1+4anQc/cLop8mCe5MoqyBefOLQ1ejlg6bCJN1YHOhzPowenOlfnVHbXnvQkf6LvBIqBuVXH8WSF58EV+I59WUfKUXV7W9F7I+MJUVZ66hQF8zlOS7nQomWoFIISDHNIH9fbxagXLrJfSfwERjWYo8zsvxeLJwAJb5Wdf8lBvzfT/cxmgME9I/k9XKg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
